#CHEM492/CHBE494/CHBE594 Lecture 2: Math Review

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy.linalg

##Matrices and Vectors

Define a matrix and turn it into a vector.

In [ ]:
a = np.array([[1,3,5],[2,4,6]])
print(a)

#Turn matrix into a vector

###BEGIN SOLUTION
print(a.flatten())
###END SOLUTION

[[1 3 5]
 [2 4 6]]
[1 3 5 2 4 6]


In [ ]:
a = np.array([0,1])
b = np.array([7,8])
print(a+b)
print(np.dot(a,b))

[7 9]
8


##Tensors
Arrays can hold tensors.

In [ ]:
rank0 = np.array(42).reshape(())
rank1 = np.array(42).reshape((1))
rank2 = np.array(42).reshape((1,1))
rank3 = np.array(42).reshape((1,1,1))
rank4 = np.array(42).reshape((1,1,1,1))

for i in range(5):
  print(locals()['rank{}'.format(i)])

42
[42]
[[42]]
[[[42]]]
[[[[42]]]]


In [ ]:
##Exercise
#Print only the element of rank4
###BEGIN SOLUTION
print(rank4[0,0,0,0])
###END SOLUTION


42


In [ ]:
#Tensor
T = np.array([
              [[0,1,2,3,4],
               [5,6,7,8,9]],
              [[10,11,12,13,14],
               [15,16,17,18,19]],
              [[20,21,22,23,24],
               [25,26,27,28,29]]
])

print(T)
print(T[0])
##What is the shape of the tensor?

###BEGIN SOLUTION
print(T.shape)
###END SOLUTION

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
(3, 2, 5)


##Matrix Addition/Multiplication

In [ ]:
#Addition
A = np.array([[1,2], [3,4]])
B = np.array([[8,7], [6,5]])
print(A)
print(B)
print(A@B)
print(np.matmul(A,B))
print(np.dot(A,B))
C = A+B

print(C)

[[1 2]
 [3 4]]
[[8 7]
 [6 5]]
[[20 17]
 [48 41]]
[[20 17]
 [48 41]]
[[20 17]
 [48 41]]
[[9 9]
 [9 9]]


In [ ]:
#Multiplication
print(np.matmul(A,B))
print(np.dot(A,B))
print(np.einsum('il,lj->ij',A,B))
print(A@B)

[[20 17]
 [48 41]]
[[20 17]
 [48 41]]
[[20 17]
 [48 41]]
[[20 17]
 [48 41]]


In [ ]:
#Order matters!
print(np.dot(B,A))

[[29 44]
 [21 32]]


## Covariance

Consider two variables x0 and x1, which corerlate perfrectly but in opposite directions.

In [ ]:
x = np.array([[0,2],[1,1],[2,0]])
print(x)


[[0 2]
 [1 1]
 [2 0]]


In [ ]:
np.cov(x)

array([[ 1., -1.],
       [-1.,  1.]])

Note how x0 increases while x1 decreases. The covariance shows this clearly.

##Matrix Inverse and Transpose

In [ ]:
A = np.array([[1,2,1],[4,4,5],[6,7,7]])
print(A)

[[1 2 1]
 [4 4 5]
 [6 7 7]]


In [ ]:
np.linalg.inv(A)

array([[-7., -7.,  6.],
       [ 2.,  1., -1.],
       [ 4.,  5., -4.]])

In [ ]:
B = np.linalg.inv(A)
print(np.linalg.inv(B))

[[1. 2. 1.]
 [4. 4. 5.]
 [6. 7. 7.]]


In [ ]:
print(A.transpose())

[[1 4 6]
 [2 4 7]
 [1 5 7]]


Use the cell below to convince yourself of the useful propertires of Matrix Transpose and Inverse.

In [ ]:
A = np.array([[1,2,1],[4,4,5],[6,7,7]])
B = np.array([[1,3,1],[3,4,5],[3,7,7]])
###BEGIN SOLUTION
Ainv = np.linalg.inv(A)
Binv = np.linalg.inv(B)
print(A@np.linalg.inv(A), np.linalg.inv(A)@A)
print(np.linalg.inv(A@B), np.linalg.inv(B)@np.linalg.inv(A))
print(np.linalg.inv(A+B), Ainv + Binv)
print(A.T.T, A)
print((A+B).T, A.T + B.T)
print((A@B).T, B.T@A.T)
###END SOLUTION

[[ 1.00000000e+00 -1.77635684e-15  8.88178420e-16]
 [-2.22044605e-15  1.00000000e+00  4.44089210e-15]
 [ 7.54951657e-15 -1.77635684e-15  1.00000000e+00]] [[ 1.00000000e+00  3.55271368e-15  3.55271368e-15]
 [ 0.00000000e+00  1.00000000e+00 -8.88178420e-16]
 [ 1.77635684e-15 -8.88178420e-16  1.00000000e+00]]
[[-4.0625 -5.625   4.5   ]
 [-2.625  -2.25    2.    ]
 [ 4.9375  5.375  -4.5   ]] [[-4.0625 -5.625   4.5   ]
 [-2.625  -2.25    2.    ]
 [ 4.9375  5.375  -4.5   ]]
[[ 0.63636364  0.95454545 -0.77272727]
 [ 0.18181818 -0.22727273  0.13636364]
 [-0.59090909 -0.38636364  0.43181818]] [[-6.5625 -6.125   5.3125]
 [ 2.375   0.75   -0.875 ]
 [ 3.4375  4.875  -3.6875]]
[[1 2 1]
 [4 4 5]
 [6 7 7]] [[1 2 1]
 [4 4 5]
 [6 7 7]]
[[ 2  7  9]
 [ 5  8 14]
 [ 2 10 14]] [[ 2  7  9]
 [ 5  8 14]
 [ 2 10 14]]
[[10 31 48]
 [18 63 95]
 [18 59 90]] [[10 31 48]
 [18 63 95]
 [18 59 90]]


##Systems of Linear Equations

Use the cell below to solve a simple system of equations.

In [ ]:
###BEGIN SOLUTION

#Begin by setting up system
'''The coefficients aij indicate the number of units of chemial i required to generate one unit of product j.


x1 +x2 + x3 =4
x1 +x2 = 3
x2+2x3 = 3

Solution: xi = [2,1,1]'''

A = np.array([[1, 1, 1],[1, 1, 0],[0,1,2]])
b = np.array([4,3,3])
print(A)
x = np.linalg.solve(A,b)
print(x)
print(np.linalg.matrix_rank(A))
###END SOLUTION

[[1 1 1]
 [1 1 0]
 [0 1 2]]
[2. 1. 1.]
3


##Eigenvectors and Eigenvalues

In [ ]:
###BEGIN SOLUTION
A = np.array([[4,2],[1,3]])
B = np.array([[2,1],[0,2]])

print(np.linalg.eig(A), np.linalg.eig(B))
###END SOLUTION

(array([5., 2.]), array([[ 0.89442719, -0.70710678],
       [ 0.4472136 ,  0.70710678]])) (array([2., 2.]), array([[ 1.0000000e+00, -1.0000000e+00],
       [ 0.0000000e+00,  4.4408921e-16]]))


##Matrix Decomposition

In [ ]:
A = np.array([[5,7,6,5],[7,10,8,7],[6,8,10,9],[5,7,9,10]])
print(A)

[[ 5  7  6  5]
 [ 7 10  8  7]
 [ 6  8 10  9]
 [ 5  7  9 10]]


In [ ]:
L = np.linalg.cholesky(A)
print(L)

[[ 2.23606798  0.          0.          0.        ]
 [ 3.13049517  0.4472136   0.          0.        ]
 [ 2.68328157 -0.89442719  1.41421356  0.        ]
 [ 2.23606798  0.          2.12132034  0.70710678]]


In [ ]:
print(L@L.T)

[[ 5.  7.  6.  5.]
 [ 7. 10.  8.  7.]
 [ 6.  8. 10.  9.]
 [ 5.  7.  9. 10.]]


In [ ]:
u,s,vT = np.linalg.svd(A)


In [ ]:
u@np.diag(s)@vT

array([[ 5.,  7.,  6.,  5.],
       [ 7., 10.,  8.,  7.],
       [ 6.,  8., 10.,  9.],
       [ 5.,  7.,  9., 10.]])

In [ ]:
e, P = np.linalg.eig(A)
print(e)

[3.02886853e+01 3.85805746e+00 1.01500484e-02 8.43107150e-01]


In [ ]:
D = np.diag(e)
print(D)

[[3.02886853e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 3.85805746e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.01500484e-02 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 8.43107150e-01]]


In [ ]:
print(P@D@P.T)

[[ 5.  7.  6.  5.]
 [ 7. 10.  8.  7.]
 [ 6.  8. 10.  9.]
 [ 5.  7.  9. 10.]]


In [ ]:
###BEGIN SOLUTION
A = np.array([[-1,-1,1,1,0,0],
              [-1,-2,0,2,1,0],
              [-1,0,0,-2,0,1],
              [-1,0,2,0,-1,0],
              [0,-1,-1,1,1,0]])

P,L,U = scipy.linalg.lu(A)

print(U)
###END SOLUTION

[[-1. -1.  1.  1.  0.  0.]
 [ 0. -1. -1.  1.  1.  0.]
 [ 0.  0. -2. -2.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
